# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10S5UDtrWZX3BFjwRdRArz5Rv-YAbxI5K
"""



"""Problem Solving

1) Write a program that adds numbers and returns the result
"""

def sum_numbers(numbers):
  #Define a variable to store the sum of numbers in it
  numtotal=0
  #loop all elements
  for num in numbers:
  #Add the item to the sum of numbers(numtotal)
    numtotal+=num
  #returns sum of numbers(numtotal)
  return numtotal
#call sum_numbers function
sum_numbers((3,4,5,6,7,8,9,2))

"""2)Write a program that reverse the contents of a strimg and prints the result."""

def revers_string(yourstring):
  #Define a variable to store the revers sring
  rev_str=""
  #Define a variable to store tle length of yourstring
  index=len(yourstring)
  #loop all string elements
  while index >0:
    rev_str+=yourstring[index-1]
    index-=1
  return rev_str
#call revers_string Function
revers_string("Duaa")

"""Write a program that counts the uppercase and lowercase letters in a string and returns their number."""

def count_upper_lower(yourstring):
  #Define a set to store numbers in it
  set_count={"upper_case":0, "lower_case":0}
  #loop all string elements
  for element in yourstring:
    if element.isupper():
      set_count["upper_case"]+=1
    if element.islower():
      set_count["lower_case"]+=1
    else:
      pass
  print("Your String :",yourstring)
  print("Upper Case in Your String is:",set_count["upper_case"])
  print("Lower Case in Your String is:",set_count["lower_case"])
#call  count_upper_lower function
count_upper_lower("Duaa Hashem Mohammad Swalmeh")

"""Write a program that enters a list containing a set of numbers that are repeated and returns a list without repeating."""

def no_repeat(YourList):
  #Define a set to store  not repeated numbers in it
  not_repeat_list=[]
  #loop all List elements
  for element in YourList:
    if element not in not_repeat_list:
      not_repeat_list.append(element)
  return not_repeat_list
#call no_rapeat function
no_repeat([1,2,1,2,3,4,5,5])

"""Write a program that you enter a number into and returns if the number is prime or not."""



def prime_numbers(number):
  #1 , 2 not prime numbers(fact)
  if number==1 or number==2:
    return False
  #We calculate the remainder of dividing the number(%) by the numbers less than it up to (2)
  else:
    for num in range (2,number):
      if number % num ==0:
        return False
      return True
#call  prime_numbers function
print(prime_numbers(5))

"""Write a program that gives you a list of numbers and returns even  & odd numbers."""

def odd_even_test(numbersList):
  #list to store even numbers
  even_list=[]
  #list to store odd numbers
  odd_list=[]
  #calculate the remainder of dividing the number(%) by  2
  for number in numbersList:
    if number % 2 ==0:
       even_list.append(number)
    else:
       odd_list.append(number)
  return ("Even numbers is:", even_list , "Even numbers is:" , odd_list)
#call odd_even_test function
odd_even_test([2,3,4,5])